# Use `pre-commit autoupdate` to update this

default_language_version:
  python: python3.12
exclude: 'migrations/.*|.*\.(min\.js|svg|json)$'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      #- id: check-yaml
      #- id: check-json
      - id: double-quote-string-fixer
      - id: end-of-file-fixer

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/google/yapf
    rev: v0.40.2
    hooks:
      - id: yapf

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args:
          - --keep-percent-format
          - --py3-plus

  - repo: https://github.com/pycqa/flake8
    rev: '7.0.0'
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-django
          - flake8-blind-except
          # - flake8-commas
          - flake8-comprehensions
          # - flake8-deprecated
          # - flake8-docstrings
          # - flake8-meiqia
          # - flake8-mutable
          # - flake8-pep3101
          # - flake8-quotes
          - flake8-string-format
          # - flake8-tidy-imports
        # stages: [ manual ]

  - repo: https://github.com/pycqa/bandit
    rev: '1.7.7'
    hooks:
      - id: bandit
        # stages: [ manual ]
        args: ["--ini=setup.cfg"]
