[build-system]
requires = ["setuptools>=61.2", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "django-richmin"
version = "0.3.5"
description = "Customized lte-bootstrap django admin theme with some useful tools"
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.6"
license = {text = "MIT License"}
authors = [
  {name = "my47", email = "mymy47@gmail.com"}
]
keywords = []
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Web Environment",
  "Framework :: Django",
  "Intended Audience :: Developers",
  "Intended Audience :: System Administrators",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Framework :: Django :: 4.0",
  "Framework :: Django :: 4.1",
  "Framework :: Django :: 4.2",
  "Framework :: Django :: 5.0",
  "Framework :: Django :: 5.1",
  "Framework :: Django :: 5.2",
  "Topic :: Software Development",
  "Topic :: Software Development :: User Interfaces",
]
dependencies = [
  "django>4,<6",
]

[project.urls]
Homepage = "https://github.com/mymy47/django-richmin"

[tool.setuptools]
include-package-data = true

[tool.setuptools_scm]
version_file = "__tmp_version.py"

[tool.pip-tools]
generate-hashes = false
verbose = true
no-emit-index-url = true
no-emit-trusted-host = true

[tool.ruff]
line-length = 120
indent-width = 4
exclude = [
  ".eggs",
  ".git",
  ".venv",
  "build",
  "dist",
  "migrations",
]
format = { quote-style = "single" }

[tool.ruff.lint]
select = [
  "I", # isort
  "S", # bandit
  "F", # Pyflakes
  "E", # pycodestyle
  "B", # flake8-bugbear
  "UP", # pyupgrade
  "SIM", # flake8-simplify
  "FA", # flake8-future-annotations
  "RSE", # flake8-raise
  "RET", # flake8-return
  "FLY", # flynt
  "DJ", # flake8-django
  "C90", # mccabe
  "PIE", # flake8-pie
  "PLW", # pylint warnings
  "PLE", # pylint errors
]

ignore = [
  "F405", # X may be undefined, or defined from star imports Y
  "B904", # Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None` to distinguish them from errors in exception handling
  "RET502", # Do not implicitly return None in function able to return non-None value
  "RET503", # Missing explicit return at the end of function able to return non-None value
  "RET504", # Unnecessary assignment to {name} before return statement
  "C901", # Too complex code
  "S101", # Use of assert
  "S311", # Standard pseudo-random
  "S607", # Starting a process with a partial executable path
]

flake8-bandit = { }
pyupgrade = { }

[tool.ruff.lint.isort]
case-sensitive = true
combine-as-imports = true
no-lines-before = ["local-folder"]
relative-imports-order = "closest-to-furthest"
